# Generated by Django 4.2 on 2023-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=200)),
                ('EmpEmail', models.CharField(max_length=200)),
                ('EmpDepartment', models.CharField(max_length=50)),
                ('EmpDescription', models.TextField()),
                ('Empfile', models.ImageField(upload_to='')),
            ],
        ),
    ]
