# Generated by Django 4.2 on 2023-05-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empIncentivedet', '0002_alter_employee_empfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Empfile',
            field=models.ImageField(upload_to='employee/images'),
        ),
    ]
