# Generated by Django 4.2 on 2023-05-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empIncentivedet', '0009_alter_employee_empfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpDepartment',
            field=models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Accounts', 'Accounts'), ('Finance', 'Fianace')], max_length=50),
        ),
    ]
