# Generated by Django 4.2 on 2023-05-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empIncentivedet', '0011_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmpPass',
            field=models.CharField(default='', max_length=100),
        ),
    ]
